config/routes.rb
StrsBackend::Application.routes.draw do
  resources :orders
  resources :taxis
  post "/orders/:id/accept", :to => "orders#accept"
  post "/orders/:id/reject", :to => "orders#reject"
  match '*all' => "application#cors_preflight", :constraints => {:method => "OPTIONS"}

end

app/models/taxi.rb
class Taxi < ActiveRecord::Base
  attr_accessible :location, :name, :status
end

app/controllers/taxis_controller.rb
class TaxisController < ApplicationController
  # GET /taxis
  # GET /taxis.json
  def index
    @taxis = Taxi.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @taxis }
    end
  end

  # GET /taxis/1
  # GET /taxis/1.json
  def show
    @taxi = Taxi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @taxi }
    end
  end

  # GET /taxis/new
  # GET /taxis/new.json
  def new
    @taxi = Taxi.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @taxi }
    end
  end

  # GET /taxis/1/edit
  def edit
    @taxi = Taxi.find(params[:id])
  end

  # POST /taxis
  # POST /taxis.json
  def create
    @taxi = Taxi.new(params[:taxi])

    respond_to do |format|
      if @taxi.save
        format.html { redirect_to @taxi, notice: 'Taxi was successfully created.' }
        format.json { render json: @taxi, status: :created, location: @taxi }
      else
        format.html { render action: "new" }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /taxis/1
  # PUT /taxis/1.json
  def update
    @taxi = Taxi.find(params[:id])

    respond_to do |format|
      if @taxi.update_attributes(params[:taxi])
        format.html { redirect_to @taxi, notice: 'Taxi was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @taxi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taxis/1
  # DELETE /taxis/1.json
  def destroy
    @taxi = Taxi.find(params[:id])
    @taxi.destroy

    respond_to do |format|
      format.html { redirect_to taxis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/taxis_helper.rb
module TaxisHelper
end

app/views/taxis/_form.html.haml
= form_for @taxi, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :location, :class => 'control-label'
    .controls
      = f.text_field :location, :class => 'text_field'
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), taxis_path, :class => 'btn'

app/views/taxis/edit.html.haml
- model_class = Taxi
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/taxis/index.html.haml
- model_class = Taxi
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:location)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @taxis.each do |taxi|
      %tr
        %td= link_to taxi.id, taxi_path(taxi)
        %td= taxi.location
        %td= taxi.status
        %td= taxi.name
        %td=l taxi.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_taxi_path(taxi), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), taxi_path(taxi), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_taxi_path, :class => 'btn btn-primary'

app/views/taxis/new.html.haml
- model_class = Taxi
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/taxis/show.html.haml
- model_class = Taxi
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:location) + ':'
  %br
  = @taxi.location
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @taxi.status
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @taxi.name

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), taxis_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_taxi_path(@taxi), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), taxi_path(@taxi), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'