config/routes.rb
StrsBackend::Application.routes.draw do
  resources :orders
  resources :taxis
  post "/orders/:id/accept", :to => "orders#accept"
  post "/orders/:id/reject", :to => "orders#reject"
  match '*all' => "application#cors_preflight", :constraints => {:method => "OPTIONS"}

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :cost, :customer_name, :customer_phone, :end_date, :end_location, :start_date, :start_location, :status, :taxi_id, :distance, :duration, :pickup_time
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    # key = 'key=AIzaSyCkauJJVLMKqj4rSpHAPgj6uj7sjsK2Em4'
    # gcmUrl = 'https://android.googleapis.com/gcm/send'
    # body = {
    #     :registration_ids => ['APA91bGEWeBeyUkCw4QooOY1MuqDWmHR5A8X2iX3vUGfJ35fRBrrEch69a0QyDDrAi8LetItT_1n5ec-vz1dsD-aJFszGjjxhv9v5xjcBAlCtjYwXPjlT2AVxgsI7BwWMjN6b7mUl6vqzSylVWAPlLBcQUyOATbKMOwIqg867gH_EcqRex-aeLs'],
    #     :data => {:message => "Hello Android ... it's Ruby!"}
    # }
    # response = RestClient.post gcmUrl, body.to_json,
    #                            {:content_type => :json, :authorization => key}
    # SuckerPunch.logger.info "Notification sent via GCM"
    # SuckerPunch.logger.info "GCM Response: #{response}"

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json

  # def create
  #   #booking = params[:booking]
  #   BookingsAsyncJob.new.async.perform("Your booking has been confirmed", nil)
  #   render :text => {:message => 'Information is being processed'}.to_json, :status => :created
  # end

  def create
    @order = Order.new(params[:order])
    @order.status = "Looking for closest Taxi"
    @order.save!
    if @order.pickup_time == ''
      BookingsAsyncJob.new.async.perform(@order, params[:device_id])
      render :text => {:message => 'Submitted information is being processed'}.to_json, :status => :created
    else
      BookingsAsyncJob.get_wait_time(@order.pickup_time, 15)
      BookingsAsyncJob.new.async.perform_deferred(@order)
      m = 'Your taxi will arrive at ' + @order.pickup_time
      render :text => {:message => m}.to_json, :status => :created
    end


    #BookingsAsyncJob.new.async.perform(params[:order], params[:device_id])

    #BookingsAsyncJob.new.async.perform(@order, params[:device_id])
    #BookingsAsyncJob.new.async.perform_deferred(10, @order)


#     @order = Order.new(params[:order])

#     respond_to do |format|
#       if @order.save
#         format.html { render :text => {:message => 'Submitted information is being processed'}.to_json, :status => :created }
#
#         #format.html { redirect_to @order, notice: 'Order was successfully created.' }
# #        format.json { render json: @order, status: :created, location: @order }
#
#         format.json { render :text => {:message => 'Submitted information is being processed'}.to_json, :status => :created }
#
#       else
#         format.html { render action: "new" }
#         format.json { render json: @order.errors, status: :unprocessable_entity }
#       end
#     end
  end



  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end


  # PUT /orders/1
  # PUT /orders/1.json
  def accept
    @order = Order.find(params[:id])
    @order.status = "Order accepted"
    @order.save

    render :text => {:message => 'Order was successfully updated.'}.to_json, :status => :created

    message = 'Your taxi will arrive in: ' + @order.duration
    Pusher['bookings'].trigger('async_notification', {:message => message})
    SuckerPunch.logger.info "Notification sent via Pusher"
  end

  def reject
    @order = Order.find(params[:id])
    @order.status = "Order rejected"
    @order.taxi_id = ''
    @order.save

    render :text => {:message => 'Order was successfully updated.'}.to_json, :status => :created

    message = 'No taxis are available'
    Pusher['bookings'].trigger('async_notification', {:message => message})
    SuckerPunch.logger.info "Notification sent via Pusher"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :start_location, :class => 'control-label'
    .controls
      = f.text_field :start_location, :class => 'text_field'
  .control-group
    = f.label :end_location, :class => 'control-label'
    .controls
      = f.text_field :end_location, :class => 'text_field'
  .control-group
    = f.label :start_date, :class => 'control-label'
    .controls
      = f.datetime_select :start_date, :class => 'datetime_select'
  .control-group
    = f.label :end_date, :class => 'control-label'
    .controls
      = f.datetime_select :end_date, :class => 'datetime_select'
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'
  .control-group
    = f.label :customer_name, :class => 'control-label'
    .controls
      = f.text_field :customer_name, :class => 'text_field'
  .control-group
    = f.label :customer_phone, :class => 'control-label'
    .controls
      = f.text_field :customer_phone, :class => 'text_field'
  .control-group
    = f.label :taxi_id, :class => 'control-label'
    .controls
      = f.number_field :taxi_id, :class => 'number_field'
  .control-group
    = f.label :cost, :class => 'control-label'
    .controls
      = f.text_field :cost, :class => 'text_field'
  .control-group
    = f.label :distance, :class => 'control-label'
    .controls
      = f.text_field :distance, :class => 'text_field'
  .control-group
    = f.label :duration, :class => 'control-label'
    .controls
      = f.text_field :duration, :class => 'text_field'
  .control-group
    = f.label :pickup_time, :class => 'control-label'
    .controls
      = f.text_field :pickup_time, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), orders_path, :class => 'btn'

app/views/orders/edit.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/orders/index.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:start_location)
      %th= model_class.human_attribute_name(:end_location)
      %th= model_class.human_attribute_name(:start_date)
      %th= model_class.human_attribute_name(:end_date)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:customer_name)
      %th= model_class.human_attribute_name(:customer_phone)
      %th= model_class.human_attribute_name(:taxi_id)
      %th= model_class.human_attribute_name(:cost)
      %th= model_class.human_attribute_name(:distance)
      %th= model_class.human_attribute_name(:duration)
      %th= model_class.human_attribute_name(:pickup_time)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @orders.each do |order|
      %tr
        %td= link_to order.id, order_path(order)
        %td= order.start_location
        %td= order.end_location
        %td= order.start_date
        %td= order.end_date
        %td= order.status
        %td= order.customer_name
        %td= order.customer_phone
        %td= order.taxi_id
        %td= order.cost
        %td= order.distance
        %td= order.duration
        %td= order.pickup_time
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_order_path(order), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), order_path(order), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_order_path, :class => 'btn btn-primary'

app/views/orders/new.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"
blaa

app/views/orders/show.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:start_location) + ':'
  %br
  = @order.start_location
%p
  %strong= model_class.human_attribute_name(:end_location) + ':'
  %br
  = @order.end_location
%p
  %strong= model_class.human_attribute_name(:start_date) + ':'
  %br
  = @order.start_date
%p
  %strong= model_class.human_attribute_name(:end_date) + ':'
  %br
  = @order.end_date
%p
  %strong= model_class.human_attribute_name(:status) + ':'
  %br
  = @order.status
%p
  %strong= model_class.human_attribute_name(:customer_name) + ':'
  %br
  = @order.customer_name
%p
  %strong= model_class.human_attribute_name(:customer_phone) + ':'
  %br
  = @order.customer_phone
%p
  %strong= model_class.human_attribute_name(:taxi_id) + ':'
  %br
  = @order.taxi_id
%p
  %strong= model_class.human_attribute_name(:cost) + ':'
  %br
  = @order.cost
%p
  %strong= model_class.human_attribute_name(:distance) + ':'
  %br
  = @order.distance
%p
  %strong= model_class.human_attribute_name(:duration) + ':'
  %br
  = @order.duration
%p
  %strong= model_class.human_attribute_name(:pickup_time) + ':'
  %br
  = @order.pickup_time

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), orders_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_order_path(@order), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), order_path(@order), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'